### ISSUE TITLE
[logging]  Rename appender type

### ISSUE THREAD

**Issue by fabito** [fabito/dropwizard-stackdriver#14]
Currently the appender type is called `GKEConsole`.

```yaml
logging:
  level: INFO
  loggers:
    io.github.fabito: TRACE
  appenders:
  - type: GKEConsole
    threshold: ALL
    timeZone: UTC
    target: stdout
```

Find out a more meaningful name, maybe: `stackdriver-console` ?
